jwt:
  secret: 3487vtnh3248392lsdifn3409asdngcvbsndaweoysn
  lifetime: 30m
  refresh_lifetime: 30d
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true